name: tahiti_example
description: Demonstrates how to use the tahiti plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  tahiti:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/stickers/pig/pig.png
    - assets/stickers/pig/8.png
    - assets/stickers/pig/9.png
    - assets/stickers/pig/14.png
    - assets/stickers/pig/15.png
    - assets/stickers/pig/16.png
    - assets/stickers/pig/12.png
    - assets/stickers/pig/13.png
    - assets/stickers/pig/11.png
    - assets/stickers/pig/10.png
    - assets/stickers/pig/4.png
    - assets/stickers/pig/5.png
    - assets/stickers/pig/7.png
    - assets/stickers/pig/6.png
    - assets/stickers/pig/2.png
    - assets/stickers/pig/3.png
    - assets/stickers/pig/1.png
    - assets/stickers/giraffe/giraffe.png
    - assets/stickers/giraffe/8.png
    - assets/stickers/giraffe/9.png
    - assets/stickers/giraffe/14.png
    - assets/stickers/giraffe/15.png
    - assets/stickers/giraffe/16.png
    - assets/stickers/giraffe/12.png
    - assets/stickers/giraffe/13.png
    - assets/stickers/giraffe/11.png
    - assets/stickers/giraffe/10.png
    - assets/stickers/giraffe/4.png
    - assets/stickers/giraffe/5.png
    - assets/stickers/giraffe/7.png
    - assets/stickers/giraffe/6.png
    - assets/stickers/giraffe/2.png
    - assets/stickers/giraffe/3.png
    - assets/stickers/giraffe/1.png
    - assets/stickers/monkey/monkey.png
    - assets/stickers/monkey/8.png
    - assets/stickers/monkey/9.png
    - assets/stickers/monkey/14.png
    - assets/stickers/monkey/15.png
    - assets/stickers/monkey/16.png
    - assets/stickers/monkey/12.png
    - assets/stickers/monkey/13.png
    - assets/stickers/monkey/11.png
    - assets/stickers/monkey/10.png
    - assets/stickers/monkey/4.png
    - assets/stickers/monkey/5.png
    - assets/stickers/monkey/7.png
    - assets/stickers/monkey/6.png
    - assets/stickers/monkey/2.png
    - assets/stickers/monkey/3.png
    - assets/stickers/monkey/1.png
    - assets/stickers/doggie/doggie.png
    - assets/stickers/doggie/8.png
    - assets/stickers/doggie/9.png
    - assets/stickers/doggie/14.png
    - assets/stickers/doggie/15.png
    - assets/stickers/doggie/16.png
    - assets/stickers/doggie/12.png
    - assets/stickers/doggie/13.png
    - assets/stickers/doggie/11.png
    - assets/stickers/doggie/10.png
    - assets/stickers/doggie/4.png
    - assets/stickers/doggie/5.png
    - assets/stickers/doggie/7.png
    - assets/stickers/doggie/6.png
    - assets/stickers/doggie/2.png
    - assets/stickers/doggie/3.png
    - assets/stickers/doggie/1.png
    - assets/stickers/carpie/carpie.png
    - assets/stickers/carpie/8.png
    - assets/stickers/carpie/9.png
    - assets/stickers/carpie/14.png
    - assets/stickers/carpie/15.png
    - assets/stickers/carpie/16.png
    - assets/stickers/carpie/12.png
    - assets/stickers/carpie/13.png
    - assets/stickers/carpie/11.png
    - assets/stickers/carpie/10.png
    - assets/stickers/carpie/4.png
    - assets/stickers/carpie/5.png
    - assets/stickers/carpie/7.png
    - assets/stickers/carpie/6.png
    - assets/stickers/carpie/2.png
    - assets/stickers/carpie/3.png
    - assets/stickers/carpie/1.png
    - assets/stickers/emoguy/happy.png
    - assets/stickers/emoguy/angry.gif
    - assets/stickers/emoguy/cold.gif
    - assets/stickers/emoguy/cry.gif
    - assets/stickers/emoguy/happy.gif
    - assets/stickers/emoguy/irritated.gif
    - assets/stickers/emoguy/laughing.gif
    - assets/stickers/emoguy/love.gif
    - assets/stickers/emoguy/playing.gif
    - assets/stickers/emoguy/relaxed.gif
    - assets/stickers/emoguy/sad.gif
    - assets/stickers/emoguy/scared.gif
    - assets/stickers/emoguy/sleeping.gif
    - assets/stickers/emoguy/thumbsdown.gif
    - assets/stickers/emoguy/thumbup.gif
    - assets/stickers/emoguy/workingout.gif
    - assets/stickers/emoguy/yummy.gif

    # template
    - assets/templates/LionSA1.svg

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
