name: tahiti_example
description: Demonstrates how to use the tahiti plugin.

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.6.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  simple_permissions: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  tahiti:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:  
    - assets/templates/LionSA1.svg
    - assets/templates/pattern.svg
    - assets/templates/pattern1.svg
    - assets/roller_image/sample1.jpg
    - assets/roller_image/sample2.jpg
    - assets/roller_image/sample3.jpg
    - assets/roller_image/sample4.jpg
    - assets/roller_image/sample5.jpg
    - assets/filter_image/filterImage1.png
    - assets/filter_image/filterImage2.png
    - assets/filter_image/filterImage3.png
    - assets/filter_image/filterImage4.png
    - assets/filter_image/filterImage5.png
    - assets/filter_image/filterImage6.png
    - assets/nima_animation/
    - assets/masking/
    
   # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Chela one
      fonts:
        - asset: assets/fonts/ChelaOne-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah.ttf
    - family: Great vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Homemade apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Kirang Haerang
      fonts:
        - asset: assets/fonts/KirangHaerang-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Patrick Hand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rock salt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Shadows into light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight.ttf
    

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
