name: tahiti
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
  flutter_svg: ^0.5.1
  audio_recorder: ^0.0.4
  audioplayer2: ^0.5.1
  path_provider: ^0.4.1
  scoped_model: ^0.3.0
  image_picker: ^0.4.6
  video_player:
  uuid: ^1.0.3
  image: ^2.0.4
  json_annotation: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.1
  json_serializable: ^1.2.1
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: org.chimple.tahiti
    pluginClass: TahitiPlugin
  assets:
    - assets/menu/pig.png
    - assets/stickers/pig/8.png
    - assets/stickers/pig/9.png
    - assets/stickers/pig/14.png
    - assets/stickers/pig/15.png
    - assets/stickers/pig/16.png
    - assets/stickers/pig/12.png
    - assets/stickers/pig/13.png
    - assets/stickers/pig/11.png
    - assets/stickers/pig/10.png
    - assets/stickers/pig/4.png
    - assets/stickers/pig/5.png
    - assets/stickers/pig/7.png
    - assets/stickers/pig/6.png
    - assets/stickers/pig/2.png
    - assets/stickers/pig/3.png
    - assets/stickers/pig/1.png
    - assets/menu/giraffe.png
    - assets/stickers/giraffe/8.png
    - assets/stickers/giraffe/9.png
    - assets/stickers/giraffe/14.png
    - assets/stickers/giraffe/15.png
    - assets/stickers/giraffe/16.png
    - assets/stickers/giraffe/12.png
    - assets/stickers/giraffe/13.png
    - assets/stickers/giraffe/11.png
    - assets/stickers/giraffe/10.png
    - assets/stickers/giraffe/4.png
    - assets/stickers/giraffe/5.png
    - assets/stickers/giraffe/7.png
    - assets/stickers/giraffe/6.png
    - assets/stickers/giraffe/2.png
    - assets/stickers/giraffe/3.png
    - assets/stickers/giraffe/1.png
    - assets/menu/monkey.png
    - assets/stickers/monkey/8.png
    - assets/stickers/monkey/9.png
    - assets/stickers/monkey/14.png
    - assets/stickers/monkey/15.png
    - assets/stickers/monkey/16.png
    - assets/stickers/monkey/12.png
    - assets/stickers/monkey/13.png
    - assets/stickers/monkey/11.png
    - assets/stickers/monkey/10.png
    - assets/stickers/monkey/4.png
    - assets/stickers/monkey/5.png
    - assets/stickers/monkey/7.png
    - assets/stickers/monkey/6.png
    - assets/stickers/monkey/2.png
    - assets/stickers/monkey/3.png
    - assets/stickers/monkey/1.png
    - assets/menu/doggie.png
    - assets/stickers/doggie/8.png
    - assets/stickers/doggie/9.png
    - assets/stickers/doggie/14.png
    - assets/stickers/doggie/15.png
    - assets/stickers/doggie/16.png
    - assets/stickers/doggie/12.png
    - assets/stickers/doggie/13.png
    - assets/stickers/doggie/11.png
    - assets/stickers/doggie/10.png
    - assets/stickers/doggie/4.png
    - assets/stickers/doggie/5.png
    - assets/stickers/doggie/7.png
    - assets/stickers/doggie/6.png
    - assets/stickers/doggie/2.png
    - assets/stickers/doggie/3.png
    - assets/stickers/doggie/1.png
    - assets/menu/carpie.png
    - assets/stickers/carpie/8.png
    - assets/stickers/carpie/9.png
    - assets/stickers/carpie/14.png
    - assets/stickers/carpie/15.png
    - assets/stickers/carpie/16.png
    - assets/stickers/carpie/12.png
    - assets/stickers/carpie/13.png
    - assets/stickers/carpie/11.png
    - assets/stickers/carpie/10.png
    - assets/stickers/carpie/4.png
    - assets/stickers/carpie/5.png
    - assets/stickers/carpie/7.png
    - assets/stickers/carpie/6.png
    - assets/stickers/carpie/2.png
    - assets/stickers/carpie/3.png
    - assets/stickers/carpie/1.png
    - assets/menu/happy.png
    - assets/stickers/emoguy/angry.gif
    - assets/stickers/emoguy/cold.gif
    - assets/stickers/emoguy/cry.gif
    - assets/stickers/emoguy/happy.gif
    - assets/stickers/emoguy/irritated.gif
    - assets/stickers/emoguy/laughing.gif
    - assets/stickers/emoguy/love.gif
    - assets/stickers/emoguy/playing.gif
    - assets/stickers/emoguy/relaxed.gif
    - assets/stickers/emoguy/sad.gif
    - assets/stickers/emoguy/scared.gif
    - assets/stickers/emoguy/sleeping.gif
    - assets/stickers/emoguy/thumbsdown.gif
    - assets/stickers/emoguy/thumbup.gif
    - assets/stickers/emoguy/workingout.gif
    - assets/stickers/emoguy/yummy.gif
    - assets/menu/camera.png
    - assets/camera/camera1.png
    - assets/camera/gallery.png 
    - assets/camera/video.png
    - assets/menu/brush.png
    - assets/menu/brush1.png
    - assets/menu/bucket.png
    - assets/menu/eraser.png
    - assets/menu/pencil.png
    - assets/menu/roller.png
    - assets/drawing/size1.png
    - assets/drawing/size2.png
    - assets/drawing/size3.png
    - assets/drawing/size4.png
    - assets/drawing/size5.png
    - assets/menu/mic.png
    - assets/mic/mic.png
    - assets/mic/play.png
    - assets/mic/stop.png
    - assets/text.png
    - assets/icon.png
    - assets/svgimage/men1.svg
    - assets/svgimage/men2.svg
    - assets/svgimage/monkey1.svg
    - assets/svgimage/monkey2.svg
    - assets/svgimage/pen1.svg
    - assets/svgimage/pen2.svg
    - assets/svgimage/pot1.svg
    - assets/svgimage/pot2.svg
    - assets/svgimage/carrot1.svg
    - assets/svgimage/carrot2.svg
    - assets/svgimage/bat1.svg
    - assets/svgimage/bat2.svg
    - assets/svgimage/ball1.svg
    - assets/svgimage/ball2.svg
    - assets/filter_icon.jpg
    - assets/filter_image/default.png
    - assets/filter_image/black_white.png
    - assets/filter_image/emboss.png
    - assets/filter_image/sepia.png
    - assets/filter_image/sobel.png
    - assets/filter_image/vignette.png
    - assets/filter_image/contrast.png
    - assets/roller_image/sample1.jpg
    - assets/roller_image/sample2.jpg
    - assets/roller_image/sample3.jpg
    - assets/roller_image/sample4.jpg
    - assets/roller_image/sample5.jpg
    
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Chela one
      fonts:
        - asset: assets/fonts/ChelaOne-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah.ttf
    - family: Great vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Homemade apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Kirang Haerang
      fonts:
        - asset: assets/fonts/KirangHaerang-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Patrick Hand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rock salt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Shadows into light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight.ttf
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"